/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0f131d',
        surface: '#0f131d',
        'surface-container-lowest': '#0a0e17',
        'surface-container-low': '#171c25',
        'surface-container': '#1b2029',
        'surface-container-high': '#262a34',
        'surface-container-highest': '#31353f',
        'surface-variant': '#31353f',
        'surface-bright': '#353944',
        'on-surface': '#dfe2f0',
        'on-surface-variant': '#d0c5b2',
        primary: '#e6c364',
        'primary-container': '#c9a84c',
        'on-primary': '#3d2e00',
        'on-primary-container': '#503d00',
        secondary: '#adc8f5',
        'secondary-container': '#2f4a70',
        'on-secondary-container': '#9fbae6',
        tertiary: '#78daaa',
        'tertiary-container': '#5cbe90',
        outline: '#99907e',
        'outline-variant': '#4d4637',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'inverse-surface': '#dfe2f0',
        'surface-tint': '#e6c364',
        'primary-fixed': '#ffe08f',
        'primary-fixed-dim': '#e6c364',
      },
      fontFamily: {
        display: ['"Bebas Neue"', 'sans-serif'],
        headline: ['"Bebas Neue"', 'sans-serif'],
        body: ['"Source Serif 4"', 'serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '0.02em' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '0.05em' }],
        'headline-mobile': ['32px', { lineHeight: '1.2' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1440px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
