"""add movie detail fields

Revision ID: 159c44f3d12f
Revises: 9e216421e288
Create Date: 2026-06-17 12:25:23.885088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159c44f3d12f'
down_revision: Union[str, Sequence[str], None] = '9e216421e288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actors', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('director', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('tagline', sa.String(length=512), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('letterboxd_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('audience_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('tomato_meter', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('total_reviews', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('positive_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'positive_pct')
    op.drop_column('movies', 'total_reviews')
    op.drop_column('movies', 'tomato_meter')
    op.drop_column('movies', 'audience_score')
    op.drop_column('movies', 'letterboxd_rating')
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'tagline')
    op.drop_column('movies', 'director')
    op.drop_column('movies', 'actors')
    # ### end Alembic commands ###
